# SPDX-FileCopyrightText: 2026 aburow
# SPDX-License-Identifier: GPL-3.0-only

[lint]
select = ["ALL"]
ignore = ["D211", "D213"]

[lint.per-file-ignores]
"tests/test_*.py" = [
  "COM812",
  "D202",
  "E501",
  "EM101",
  "INP001",
  "PLR2004",
  "S101",
  "SLF001",
  "TC002",
  "TRY003",
]
